<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20240223085149 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE act (id INT AUTO_INCREMENT NOT NULL, hospital_id INT DEFAULT NULL, category_id INT DEFAULT NULL, wording VARCHAR(255) NOT NULL, price NUMERIC(10, 2) DEFAULT NULL, cost NUMERIC(10, 2) DEFAULT NULL, procedures JSON DEFAULT NULL, profit_marge DOUBLE PRECISION DEFAULT NULL, created_at DATETIME DEFAULT NULL, is_deleted TINYINT(1) NOT NULL, INDEX IDX_AFECF54463DBB69 (hospital_id), INDEX IDX_AFECF54412469DE2 (category_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE act_category (id INT AUTO_INCREMENT NOT NULL, hospital_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, created_at DATETIME DEFAULT NULL, is_deleted TINYINT(1) NOT NULL, INDEX IDX_30337BDC63DBB69 (hospital_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE activities (id INT AUTO_INCREMENT NOT NULL, author_id INT DEFAULT NULL, hospital_id INT DEFAULT NULL, title VARCHAR(255) DEFAULT NULL, description LONGTEXT DEFAULT NULL, slug VARCHAR(255) DEFAULT NULL, created_at DATETIME DEFAULT NULL, INDEX IDX_B5F1AFE5F675F31B (author_id), INDEX IDX_B5F1AFE563DBB69 (hospital_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE acts_invoice_basket (id INT AUTO_INCREMENT NOT NULL, invoice_id INT DEFAULT NULL, act_id INT DEFAULT NULL, price NUMERIC(10, 2) DEFAULT NULL, date VARCHAR(20) DEFAULT NULL, INDEX IDX_18E3BB2E2989F1FD (invoice_id), INDEX IDX_18E3BB2ED1A55B28 (act_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE agent (id INT AUTO_INCREMENT NOT NULL, hospital_id INT DEFAULT NULL, office_id INT DEFAULT NULL, service_id INT DEFAULT NULL, user_id INT DEFAULT NULL, user_account_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, last_name VARCHAR(255) DEFAULT NULL, first_name VARCHAR(255) DEFAULT NULL, sex VARCHAR(4) DEFAULT NULL, phone VARCHAR(255) NOT NULL, email VARCHAR(255) DEFAULT NULL, full_name VARCHAR(255) DEFAULT NULL, created_at DATETIME DEFAULT NULL, is_deleted TINYINT(1) NOT NULL, INDEX IDX_268B9C9D63DBB69 (hospital_id), INDEX IDX_268B9C9DFFA0C224 (office_id), INDEX IDX_268B9C9DED5CA9E6 (service_id), INDEX IDX_268B9C9DA76ED395 (user_id), UNIQUE INDEX UNIQ_268B9C9D3C0C9956 (user_account_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE appointment (id INT AUTO_INCREMENT NOT NULL, doctor_id INT DEFAULT NULL, consultation_id INT DEFAULT NULL, patient_id INT NOT NULL, hospital_id INT DEFAULT NULL, user_id INT DEFAULT NULL, is_complete TINYINT(1) NOT NULL, appointment_date DATETIME DEFAULT NULL, description LONGTEXT DEFAULT NULL, reason VARCHAR(255) NOT NULL, full_name VARCHAR(255) DEFAULT NULL, created_at DATETIME DEFAULT NULL, is_deleted TINYINT(1) NOT NULL, INDEX IDX_FE38F84487F4FB17 (doctor_id), UNIQUE INDEX UNIQ_FE38F84462FF6CDF (consultation_id), INDEX IDX_FE38F8446B899279 (patient_id), INDEX IDX_FE38F84463DBB69 (hospital_id), INDEX IDX_FE38F844A76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE bed (id INT AUTO_INCREMENT NOT NULL, hospital_id INT DEFAULT NULL, bedroom_id INT DEFAULT NULL, number VARCHAR(255) NOT NULL, it_has_taken TINYINT(1) DEFAULT NULL, cost NUMERIC(10, 2) NOT NULL, price NUMERIC(10, 2) NOT NULL, created_at DATETIME DEFAULT NULL, is_deleted TINYINT(1) NOT NULL, INDEX IDX_E647FCFF63DBB69 (hospital_id), INDEX IDX_E647FCFFBDB6797C (bedroom_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE bedroom (id INT AUTO_INCREMENT NOT NULL, category_id INT DEFAULT NULL, hospital_id INT DEFAULT NULL, number VARCHAR(255) NOT NULL, description VARCHAR(53) DEFAULT NULL, created_at DATETIME DEFAULT NULL, is_deleted TINYINT(1) NOT NULL, INDEX IDX_E615435112469DE2 (category_id), INDEX IDX_E615435163DBB69 (hospital_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE bedroom_category (id INT AUTO_INCREMENT NOT NULL, hospital_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, created_at DATETIME DEFAULT NULL, INDEX IDX_1F4C876C63DBB69 (hospital_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE box (id INT AUTO_INCREMENT NOT NULL, hospital_id INT NOT NULL, sum NUMERIC(10, 2) DEFAULT NULL, output_sum NUMERIC(10, 2) DEFAULT NULL, INDEX IDX_8A9483A63DBB69 (hospital_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE box_expense (id INT AUTO_INCREMENT NOT NULL, hospital_id INT DEFAULT NULL, user_id INT DEFAULT NULL, category_id INT DEFAULT NULL, box_id INT DEFAULT NULL, reason VARCHAR(255) NOT NULL, recipient VARCHAR(255) NOT NULL, amount NUMERIC(10, 2) NOT NULL, doc_ref VARCHAR(255) DEFAULT NULL, created_at DATETIME DEFAULT NULL, INDEX IDX_34F8139763DBB69 (hospital_id), INDEX IDX_34F81397A76ED395 (user_id), INDEX IDX_34F8139712469DE2 (category_id), INDEX IDX_34F81397D8177B3F (box_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE box_historic (id INT AUTO_INCREMENT NOT NULL, box_id INT NOT NULL, tag VARCHAR(8) NOT NULL, amount NUMERIC(10, 2) NOT NULL, created_at DATETIME DEFAULT NULL, INDEX IDX_FC952DF2D8177B3F (box_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE box_input (id INT AUTO_INCREMENT NOT NULL, hospital_id INT DEFAULT NULL, user_id INT DEFAULT NULL, box_id INT DEFAULT NULL, reason VARCHAR(255) DEFAULT NULL, porter VARCHAR(255) NOT NULL, amount NUMERIC(10, 2) NOT NULL, doc_ref VARCHAR(255) DEFAULT NULL, created_at DATETIME DEFAULT NULL, INDEX IDX_A102EE3F63DBB69 (hospital_id), INDEX IDX_A102EE3FA76ED395 (user_id), INDEX IDX_A102EE3FD8177B3F (box_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE box_output (id INT AUTO_INCREMENT NOT NULL, hospital_id INT DEFAULT NULL, user_id INT DEFAULT NULL, category_id INT DEFAULT NULL, box_id INT DEFAULT NULL, reason VARCHAR(255) NOT NULL, recipient VARCHAR(255) NOT NULL, amount NUMERIC(10, 2) NOT NULL, doc_ref VARCHAR(255) DEFAULT NULL, created_at DATETIME DEFAULT NULL, INDEX IDX_6276540863DBB69 (hospital_id), INDEX IDX_62765408A76ED395 (user_id), INDEX IDX_6276540812469DE2 (category_id), INDEX IDX_62765408D8177B3F (box_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE consultation (id INT AUTO_INCREMENT NOT NULL, patient_id INT NOT NULL, file_id INT DEFAULT NULL, hospital_id INT DEFAULT NULL, user_id INT DEFAULT NULL, doctor_id INT DEFAULT NULL, is_complete TINYINT(1) NOT NULL, temperature NUMERIC(9, 0) DEFAULT NULL, weight NUMERIC(9, 2) DEFAULT NULL, arterial_tension VARCHAR(20) DEFAULT NULL, cardiac_frequency VARCHAR(20) DEFAULT NULL, respiratory_frequency VARCHAR(20) DEFAULT NULL, oxygen_saturation VARCHAR(20) DEFAULT NULL, note LONGTEXT DEFAULT NULL, diagnostic LONGTEXT DEFAULT NULL, comment LONGTEXT DEFAULT NULL, full_name VARCHAR(255) DEFAULT NULL, is_published TINYINT(1) NOT NULL, followed JSON DEFAULT NULL, medicines_prescriptions JSON DEFAULT NULL, treatments_descriptions LONGTEXT DEFAULT NULL, age INT DEFAULT NULL, created_at DATETIME DEFAULT NULL, is_deleted TINYINT(1) NOT NULL, INDEX IDX_964685A66B899279 (patient_id), INDEX IDX_964685A693CB796C (file_id), INDEX IDX_964685A663DBB69 (hospital_id), INDEX IDX_964685A6A76ED395 (user_id), INDEX IDX_964685A687F4FB17 (doctor_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE consultation_act (consultation_id INT NOT NULL, act_id INT NOT NULL, INDEX IDX_D236ADFE62FF6CDF (consultation_id), INDEX IDX_D236ADFED1A55B28 (act_id), PRIMARY KEY(consultation_id, act_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE consultation_exam (consultation_id INT NOT NULL, exam_id INT NOT NULL, INDEX IDX_1372260C62FF6CDF (consultation_id), INDEX IDX_1372260C578D5E91 (exam_id), PRIMARY KEY(consultation_id, exam_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE consultation_treatment (consultation_id INT NOT NULL, treatment_id INT NOT NULL, INDEX IDX_3EF32AD662FF6CDF (consultation_id), INDEX IDX_3EF32AD6471C0366 (treatment_id), PRIMARY KEY(consultation_id, treatment_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE consultations_type (id INT AUTO_INCREMENT NOT NULL, hospital_id INT DEFAULT NULL, wording VARCHAR(255) NOT NULL, price NUMERIC(10, 2) NOT NULL, created_at DATETIME DEFAULT NULL, is_deleted TINYINT(1) NOT NULL, INDEX IDX_DA0F005163DBB69 (hospital_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE consumption_unit (id INT AUTO_INCREMENT NOT NULL, hospital_id INT DEFAULT NULL, wording VARCHAR(255) NOT NULL, created_at DATETIME DEFAULT NULL, INDEX IDX_114B66C463DBB69 (hospital_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE covenant (id INT AUTO_INCREMENT NOT NULL, hospital_id INT DEFAULT NULL, logo_id INT DEFAULT NULL, file_path VARCHAR(255) DEFAULT NULL, denomination VARCHAR(255) NOT NULL, unit_name VARCHAR(20) DEFAULT NULL, focal VARCHAR(255) NOT NULL, tel VARCHAR(255) NOT NULL, email VARCHAR(255) DEFAULT NULL, address VARCHAR(255) DEFAULT NULL, created_at DATETIME DEFAULT NULL, is_deleted TINYINT(1) NOT NULL, INDEX IDX_F4EB80F763DBB69 (hospital_id), INDEX IDX_F4EB80F7F98F144A (logo_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE covenant_invoice (id INT AUTO_INCREMENT NOT NULL, hospital_id INT DEFAULT NULL, covenant_id INT DEFAULT NULL, user_id INT DEFAULT NULL, amount NUMERIC(10, 2) NOT NULL, total_amount NUMERIC(10, 2) DEFAULT NULL, paid NUMERIC(10, 2) DEFAULT NULL, leftover NUMERIC(10, 2) DEFAULT NULL, is_complete TINYINT(1) NOT NULL, v_ta DOUBLE PRECISION DEFAULT NULL, discount DOUBLE PRECISION DEFAULT NULL, released_at DATETIME DEFAULT NULL, full_name VARCHAR(255) DEFAULT NULL, sub_total NUMERIC(10, 2) DEFAULT NULL, currency VARCHAR(20) DEFAULT NULL, is_published TINYINT(1) NOT NULL, year INT DEFAULT NULL, month VARCHAR(2) DEFAULT NULL, files_price NUMERIC(10, 2) DEFAULT NULL, total_acts_baskets NUMERIC(10, 2) DEFAULT NULL, total_exams_baskets NUMERIC(10, 2) DEFAULT NULL, total_nursing_price NUMERIC(10, 2) DEFAULT NULL, hosp_price NUMERIC(10, 2) DEFAULT NULL, INDEX IDX_58A21C4463DBB69 (hospital_id), INDEX IDX_58A21C44DA91032A (covenant_id), INDEX IDX_58A21C44A76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE department (id INT AUTO_INCREMENT NOT NULL, hospital_id INT NOT NULL, name VARCHAR(255) NOT NULL, created_at DATETIME DEFAULT NULL, is_deleted TINYINT(1) NOT NULL, INDEX IDX_CD1DE18A63DBB69 (hospital_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE destock_medicine_for_hospital (id INT AUTO_INCREMENT NOT NULL, medicine_id INT DEFAULT NULL, user_id INT DEFAULT NULL, quantity DOUBLE PRECISION DEFAULT NULL, created_at DATETIME DEFAULT NULL, INDEX IDX_5CD4372F2F7D140A (medicine_id), INDEX IDX_5CD4372FA76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE destocking_of_medicines (id INT AUTO_INCREMENT NOT NULL, medicine_id INT DEFAULT NULL, user_id INT DEFAULT NULL, loss NUMERIC(10, 2) DEFAULT NULL, quantity DOUBLE PRECISION DEFAULT NULL, cost NUMERIC(10, 2) DEFAULT NULL, price NUMERIC(10, 2) DEFAULT NULL, created_at DATETIME DEFAULT NULL, INDEX IDX_535BD9F2F7D140A (medicine_id), INDEX IDX_535BD9FA76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE drugstore_supply (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, hospital_id INT DEFAULT NULL, provider_id INT DEFAULT NULL, document VARCHAR(255) NOT NULL, released DATETIME DEFAULT NULL, sub_total NUMERIC(10, 2) NOT NULL, currency VARCHAR(50) DEFAULT NULL, total NUMERIC(10, 2) DEFAULT NULL, UNIQUE INDEX UNIQ_7F862433D8698A76 (document), INDEX IDX_7F862433A76ED395 (user_id), INDEX IDX_7F86243363DBB69 (hospital_id), INDEX IDX_7F862433A53A8AA (provider_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE drugstore_supply_medicine (id INT AUTO_INCREMENT NOT NULL, drugstore_supply_id INT NOT NULL, medicine_id INT NOT NULL, cost NUMERIC(10, 2) NOT NULL, quantity INT NOT NULL, expiry_date DATETIME DEFAULT NULL, quantity_label VARCHAR(255) DEFAULT NULL, other_qty INT DEFAULT NULL, v_ta DOUBLE PRECISION DEFAULT NULL, INDEX IDX_DC49F8AB55F5935 (drugstore_supply_id), INDEX IDX_DC49F8A2F7D140A (medicine_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE exam (id INT AUTO_INCREMENT NOT NULL, hospital_id INT DEFAULT NULL, category_id INT DEFAULT NULL, wording VARCHAR(255) NOT NULL, price NUMERIC(10, 2) DEFAULT NULL, created_at DATETIME DEFAULT NULL, is_deleted TINYINT(1) NOT NULL, INDEX IDX_38BBA6C663DBB69 (hospital_id), INDEX IDX_38BBA6C612469DE2 (category_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE exam_category (id INT AUTO_INCREMENT NOT NULL, hospital_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, created_at DATETIME DEFAULT NULL, INDEX IDX_452856F263DBB69 (hospital_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE exams_invoice_basket (id INT AUTO_INCREMENT NOT NULL, invoice_id INT DEFAULT NULL, exam_id INT DEFAULT NULL, price NUMERIC(10, 2) DEFAULT NULL, INDEX IDX_7782193A2989F1FD (invoice_id), INDEX IDX_7782193A578D5E91 (exam_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE expense_category (id INT AUTO_INCREMENT NOT NULL, hospital_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, created_at DATETIME DEFAULT NULL, INDEX IDX_C02DDB3863DBB69 (hospital_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE hospital (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, logo_id INT DEFAULT NULL, denomination VARCHAR(255) NOT NULL, unit_name VARCHAR(20) DEFAULT NULL, tel VARCHAR(255) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, address VARCHAR(255) DEFAULT NULL, created_at DATETIME DEFAULT NULL, is_deleted TINYINT(1) NOT NULL, UNIQUE INDEX UNIQ_4282C85BA76ED395 (user_id), INDEX IDX_4282C85BF98F144A (logo_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE hospitalization (id INT AUTO_INCREMENT NOT NULL, consultation_id INT DEFAULT NULL, bed_id INT DEFAULT NULL, hospital_id INT DEFAULT NULL, price NUMERIC(10, 2) NOT NULL, released_at DATETIME NOT NULL, leave_at DATETIME DEFAULT NULL, days_counter INT NOT NULL, is_completed TINYINT(1) NOT NULL, full_name VARCHAR(255) DEFAULT NULL, is_deleted TINYINT(1) NOT NULL, UNIQUE INDEX UNIQ_40CF089162FF6CDF (consultation_id), INDEX IDX_40CF089188688BB9 (bed_id), INDEX IDX_40CF089163DBB69 (hospital_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE image_object (id INT AUTO_INCREMENT NOT NULL, hospital_id INT DEFAULT NULL, file_path VARCHAR(255) DEFAULT NULL, created_at DATETIME DEFAULT NULL, INDEX IDX_7B0F52463DBB69 (hospital_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE invoice (id INT AUTO_INCREMENT NOT NULL, hospital_id INT DEFAULT NULL, patient_id INT DEFAULT NULL, consultation_id INT NOT NULL, user_id INT DEFAULT NULL, amount NUMERIC(10, 2) NOT NULL, total_amount NUMERIC(10, 2) DEFAULT NULL, paid NUMERIC(10, 2) DEFAULT NULL, leftover NUMERIC(10, 2) DEFAULT NULL, is_complete TINYINT(1) NOT NULL, released_at DATETIME DEFAULT NULL, discount DOUBLE PRECISION DEFAULT NULL, v_ta DOUBLE PRECISION DEFAULT NULL, full_name VARCHAR(255) DEFAULT NULL, updated_at DATETIME DEFAULT NULL, sub_total NUMERIC(10, 2) DEFAULT NULL, currency VARCHAR(255) DEFAULT NULL, is_published TINYINT(1) NOT NULL, is_deleted TINYINT(1) NOT NULL, INDEX IDX_9065174463DBB69 (hospital_id), INDEX IDX_906517446B899279 (patient_id), UNIQUE INDEX UNIQ_9065174462FF6CDF (consultation_id), INDEX IDX_90651744A76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE invoice_storic (id INT AUTO_INCREMENT NOT NULL, invoice_id INT DEFAULT NULL, user_id INT DEFAULT NULL, nursing_id INT DEFAULT NULL, covenant_invoice_id INT DEFAULT NULL, amount NUMERIC(10, 2) NOT NULL, created_at DATETIME DEFAULT NULL, INDEX IDX_DFA4BEF72989F1FD (invoice_id), INDEX IDX_DFA4BEF7A76ED395 (user_id), INDEX IDX_DFA4BEF7936DC252 (nursing_id), INDEX IDX_DFA4BEF7CF7D7FED (covenant_invoice_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE lab (id INT AUTO_INCREMENT NOT NULL, hospital_id INT DEFAULT NULL, user_id INT DEFAULT NULL, consultation_id INT DEFAULT NULL, patient_id INT DEFAULT NULL, user_prescriber_id INT DEFAULT NULL, user_publisher_id INT DEFAULT NULL, note LONGTEXT DEFAULT NULL, comment LONGTEXT DEFAULT NULL, updated_at DATETIME DEFAULT NULL, is_published TINYINT(1) DEFAULT NULL, results JSON DEFAULT NULL, age INT DEFAULT NULL, created_at DATETIME DEFAULT NULL, full_name VARCHAR(255) DEFAULT NULL, INDEX IDX_61D6B1C463DBB69 (hospital_id), INDEX IDX_61D6B1C4A76ED395 (user_id), UNIQUE INDEX UNIQ_61D6B1C462FF6CDF (consultation_id), INDEX IDX_61D6B1C46B899279 (patient_id), INDEX IDX_61D6B1C476EF8C3F (user_prescriber_id), INDEX IDX_61D6B1C4C00413CC (user_publisher_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE lab_result (id INT AUTO_INCREMENT NOT NULL, lab_id INT DEFAULT NULL, exam_id INT DEFAULT NULL, INDEX IDX_86B24747628913D5 (lab_id), INDEX IDX_86B24747578D5E91 (exam_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE medicine (id INT AUTO_INCREMENT NOT NULL, consumption_unit_id INT DEFAULT NULL, category_id INT DEFAULT NULL, sub_category_id INT DEFAULT NULL, hospital_id INT DEFAULT NULL, user_id INT DEFAULT NULL, code VARCHAR(255) DEFAULT NULL, wording VARCHAR(255) NOT NULL, cost NUMERIC(10, 2) DEFAULT NULL, price NUMERIC(10, 2) DEFAULT NULL, quantity DOUBLE PRECISION DEFAULT NULL, expiry_date DATETIME DEFAULT NULL, days_remainder INT DEFAULT NULL, released DATETIME DEFAULT NULL, total_quantity DOUBLE PRECISION DEFAULT NULL, v_ta DOUBLE PRECISION DEFAULT NULL, created_at DATETIME DEFAULT NULL, is_deleted TINYINT(1) NOT NULL, INDEX IDX_58362A8D224EAF84 (consumption_unit_id), INDEX IDX_58362A8D12469DE2 (category_id), INDEX IDX_58362A8DF7BFE87C (sub_category_id), INDEX IDX_58362A8D63DBB69 (hospital_id), INDEX IDX_58362A8DA76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE medicine_categories (id INT AUTO_INCREMENT NOT NULL, hospital_id INT DEFAULT NULL, wording VARCHAR(255) NOT NULL, created_at DATETIME DEFAULT NULL, INDEX IDX_665A0CBA63DBB69 (hospital_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE medicine_invoice (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, hospital_id INT DEFAULT NULL, amount NUMERIC(10, 2) NOT NULL, released DATETIME DEFAULT NULL, currency VARCHAR(10) DEFAULT NULL, discount DOUBLE PRECISION DEFAULT NULL, total_amount NUMERIC(10, 2) DEFAULT NULL, v_ta DOUBLE PRECISION DEFAULT NULL, sub_total NUMERIC(10, 2) DEFAULT NULL, INDEX IDX_9D9E605AA76ED395 (user_id), INDEX IDX_9D9E605A63DBB69 (hospital_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE medicine_sub_categories (id INT AUTO_INCREMENT NOT NULL, category_id INT DEFAULT NULL, hospital_id INT DEFAULT NULL, wording VARCHAR(255) NOT NULL, created_at DATETIME DEFAULT NULL, INDEX IDX_FA70B6DE12469DE2 (category_id), INDEX IDX_FA70B6DE63DBB69 (hospital_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE medicines_sold (id INT AUTO_INCREMENT NOT NULL, medicine_id INT NOT NULL, invoice_id INT NOT NULL, quantity DOUBLE PRECISION NOT NULL, price NUMERIC(10, 2) NOT NULL, sum NUMERIC(10, 2) DEFAULT NULL, cost NUMERIC(10, 2) DEFAULT NULL, gain NUMERIC(10, 2) DEFAULT NULL, INDEX IDX_A1116C852F7D140A (medicine_id), INDEX IDX_A1116C852989F1FD (invoice_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE nursing (id INT AUTO_INCREMENT NOT NULL, consultation_id INT DEFAULT NULL, patient_id INT DEFAULT NULL, hospital_id INT DEFAULT NULL, is_published TINYINT(1) DEFAULT NULL, comment LONGTEXT DEFAULT NULL, is_completed TINYINT(1) NOT NULL, amount NUMERIC(10, 2) DEFAULT NULL, total_amount NUMERIC(10, 2) DEFAULT NULL, discount DOUBLE PRECISION DEFAULT NULL, v_ta DOUBLE PRECISION DEFAULT NULL, paid NUMERIC(10, 2) DEFAULT NULL, leftover NUMERIC(10, 2) DEFAULT NULL, full_name VARCHAR(255) DEFAULT NULL, arrival_dates JSON DEFAULT NULL, released_at_items JSON DEFAULT NULL, sub_total NUMERIC(10, 2) DEFAULT NULL, is_payed TINYINT(1) NOT NULL, currency VARCHAR(255) DEFAULT NULL, acts JSON DEFAULT NULL, age INT DEFAULT NULL, created_at DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_883C8A1462FF6CDF (consultation_id), INDEX IDX_883C8A146B899279 (patient_id), INDEX IDX_883C8A1463DBB69 (hospital_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE nursing_treatment (id INT AUTO_INCREMENT NOT NULL, nursing_id INT DEFAULT NULL, treatment_id INT DEFAULT NULL, user_id INT DEFAULT NULL, medicines JSON DEFAULT NULL, leave_at DATETIME DEFAULT NULL, price NUMERIC(10, 2) DEFAULT NULL, created_at DATETIME DEFAULT NULL, INDEX IDX_6138D4C8936DC252 (nursing_id), INDEX IDX_6138D4C8471C0366 (treatment_id), INDEX IDX_6138D4C8A76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE office (id INT AUTO_INCREMENT NOT NULL, hospital_id INT DEFAULT NULL, title VARCHAR(255) NOT NULL, created_at DATETIME DEFAULT NULL, is_deleted TINYINT(1) NOT NULL, INDEX IDX_74516B0263DBB69 (hospital_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE parameters (id INT AUTO_INCREMENT NOT NULL, hospital_id INT DEFAULT NULL, currency VARCHAR(255) NOT NULL, rate NUMERIC(10, 2) DEFAULT NULL, second_currency VARCHAR(5) DEFAULT NULL, name VARCHAR(255) NOT NULL, code VARCHAR(5) NOT NULL, second_code VARCHAR(5) DEFAULT NULL, f_operation char(1) default null, l_operation char(1) default null, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_69348FE63DBB69 (hospital_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE patient (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, covenant_id INT DEFAULT NULL, profile_id INT DEFAULT NULL, hospital_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, last_name VARCHAR(255) DEFAULT NULL, first_name VARCHAR(255) DEFAULT NULL, sex VARCHAR(255) DEFAULT NULL, birth_date DATE DEFAULT NULL, birth_place VARCHAR(255) DEFAULT NULL, marital_status VARCHAR(12) DEFAULT NULL, tel VARCHAR(255) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, father VARCHAR(255) DEFAULT NULL, mother VARCHAR(255) DEFAULT NULL, address VARCHAR(255) DEFAULT NULL, age INT DEFAULT NULL, nationality VARCHAR(255) DEFAULT NULL, full_name VARCHAR(255) DEFAULT NULL, created_at DATETIME DEFAULT NULL, is_deleted TINYINT(1) NOT NULL, private_key VARCHAR(255) DEFAULT NULL, is_private_key_exists TINYINT(1) NOT NULL, INDEX IDX_1ADAD7EBA76ED395 (user_id), INDEX IDX_1ADAD7EBDA91032A (covenant_id), INDEX IDX_1ADAD7EBCCFA12B8 (profile_id), INDEX IDX_1ADAD7EB63DBB69 (hospital_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE pdf_object (id INT AUTO_INCREMENT NOT NULL, file_path VARCHAR(255) DEFAULT NULL, created_at DATETIME DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE personal_image_object (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, file_path VARCHAR(255) DEFAULT NULL, created_at DATETIME DEFAULT NULL, INDEX IDX_E1053F56A76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE prescription (id INT AUTO_INCREMENT NOT NULL, consultation_id INT DEFAULT NULL, lab_id INT DEFAULT NULL, patient_id INT DEFAULT NULL, user_id INT DEFAULT NULL, hospital_id INT DEFAULT NULL, descriptions LONGTEXT DEFAULT NULL, updated_at DATETIME DEFAULT NULL, is_published TINYINT(1) DEFAULT NULL, orders JSON DEFAULT NULL, full_name VARCHAR(255) DEFAULT NULL, UNIQUE INDEX UNIQ_1FBFB8D962FF6CDF (consultation_id), UNIQUE INDEX UNIQ_1FBFB8D9628913D5 (lab_id), INDEX IDX_1FBFB8D96B899279 (patient_id), INDEX IDX_1FBFB8D9A76ED395 (user_id), INDEX IDX_1FBFB8D963DBB69 (hospital_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE provider (id INT AUTO_INCREMENT NOT NULL, hospital_id INT DEFAULT NULL, user_id INT DEFAULT NULL, wording VARCHAR(255) NOT NULL, focal VARCHAR(255) NOT NULL, tel VARCHAR(20) NOT NULL, email VARCHAR(255) DEFAULT NULL, address VARCHAR(255) NOT NULL, created_at DATETIME DEFAULT NULL, is_deleted TINYINT(1) NOT NULL, INDEX IDX_92C4739C63DBB69 (hospital_id), INDEX IDX_92C4739CA76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE reset_pass_notifier (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, username VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, released_at DATETIME DEFAULT NULL, code INT DEFAULT NULL, INDEX IDX_C158191CA76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE service (id INT AUTO_INCREMENT NOT NULL, hospital_id INT DEFAULT NULL, department_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, created_at DATETIME DEFAULT NULL, is_deleted TINYINT(1) NOT NULL, INDEX IDX_E19D9AD263DBB69 (hospital_id), INDEX IDX_E19D9AD2AE80F5DF (department_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE treatment (id INT AUTO_INCREMENT NOT NULL, hospital_id INT DEFAULT NULL, category_id INT DEFAULT NULL, wording VARCHAR(255) NOT NULL, price NUMERIC(10, 2) DEFAULT NULL, created_at DATETIME DEFAULT NULL, is_deleted TINYINT(1) NOT NULL, INDEX IDX_98013C3163DBB69 (hospital_id), INDEX IDX_98013C3112469DE2 (category_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE treatment_category (id INT AUTO_INCREMENT NOT NULL, hospital_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, created_at DATETIME DEFAULT NULL, INDEX IDX_94E6519863DBB69 (hospital_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, hospital_center_id INT DEFAULT NULL, profile_id INT DEFAULT NULL, username VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, email VARCHAR(255) DEFAULT NULL, tel VARCHAR(255) NOT NULL, is_active TINYINT(1) NOT NULL, name VARCHAR(255) DEFAULT NULL, created_at DATETIME DEFAULT NULL, u_id VARCHAR(255) DEFAULT NULL, is_deleted TINYINT(1) NOT NULL, UNIQUE INDEX UNIQ_8D93D649F85E0677 (username), INDEX IDX_8D93D649A76ED395 (user_id), INDEX IDX_8D93D64994CF6872 (hospital_center_id), INDEX IDX_8D93D649CCFA12B8 (profile_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('ALTER TABLE act ADD CONSTRAINT FK_AFECF54463DBB69 FOREIGN KEY (hospital_id) REFERENCES hospital (id)');
        $this->addSql('ALTER TABLE act ADD CONSTRAINT FK_AFECF54412469DE2 FOREIGN KEY (category_id) REFERENCES act_category (id)');
        $this->addSql('ALTER TABLE act_category ADD CONSTRAINT FK_30337BDC63DBB69 FOREIGN KEY (hospital_id) REFERENCES hospital (id)');
        $this->addSql('ALTER TABLE activities ADD CONSTRAINT FK_B5F1AFE5F675F31B FOREIGN KEY (author_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE activities ADD CONSTRAINT FK_B5F1AFE563DBB69 FOREIGN KEY (hospital_id) REFERENCES hospital (id)');
        $this->addSql('ALTER TABLE acts_invoice_basket ADD CONSTRAINT FK_18E3BB2E2989F1FD FOREIGN KEY (invoice_id) REFERENCES invoice (id)');
        $this->addSql('ALTER TABLE acts_invoice_basket ADD CONSTRAINT FK_18E3BB2ED1A55B28 FOREIGN KEY (act_id) REFERENCES act (id)');
        $this->addSql('ALTER TABLE agent ADD CONSTRAINT FK_268B9C9D63DBB69 FOREIGN KEY (hospital_id) REFERENCES hospital (id)');
        $this->addSql('ALTER TABLE agent ADD CONSTRAINT FK_268B9C9DFFA0C224 FOREIGN KEY (office_id) REFERENCES office (id)');
        $this->addSql('ALTER TABLE agent ADD CONSTRAINT FK_268B9C9DED5CA9E6 FOREIGN KEY (service_id) REFERENCES service (id)');
        $this->addSql('ALTER TABLE agent ADD CONSTRAINT FK_268B9C9DA76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE agent ADD CONSTRAINT FK_268B9C9D3C0C9956 FOREIGN KEY (user_account_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE appointment ADD CONSTRAINT FK_FE38F84487F4FB17 FOREIGN KEY (doctor_id) REFERENCES agent (id)');
        $this->addSql('ALTER TABLE appointment ADD CONSTRAINT FK_FE38F84462FF6CDF FOREIGN KEY (consultation_id) REFERENCES consultation (id)');
        $this->addSql('ALTER TABLE appointment ADD CONSTRAINT FK_FE38F8446B899279 FOREIGN KEY (patient_id) REFERENCES patient (id)');
        $this->addSql('ALTER TABLE appointment ADD CONSTRAINT FK_FE38F84463DBB69 FOREIGN KEY (hospital_id) REFERENCES hospital (id)');
        $this->addSql('ALTER TABLE appointment ADD CONSTRAINT FK_FE38F844A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE bed ADD CONSTRAINT FK_E647FCFF63DBB69 FOREIGN KEY (hospital_id) REFERENCES hospital (id)');
        $this->addSql('ALTER TABLE bed ADD CONSTRAINT FK_E647FCFFBDB6797C FOREIGN KEY (bedroom_id) REFERENCES bedroom (id)');
        $this->addSql('ALTER TABLE bedroom ADD CONSTRAINT FK_E615435112469DE2 FOREIGN KEY (category_id) REFERENCES bedroom_category (id)');
        $this->addSql('ALTER TABLE bedroom ADD CONSTRAINT FK_E615435163DBB69 FOREIGN KEY (hospital_id) REFERENCES hospital (id)');
        $this->addSql('ALTER TABLE bedroom_category ADD CONSTRAINT FK_1F4C876C63DBB69 FOREIGN KEY (hospital_id) REFERENCES hospital (id)');
        $this->addSql('ALTER TABLE box ADD CONSTRAINT FK_8A9483A63DBB69 FOREIGN KEY (hospital_id) REFERENCES hospital (id)');
        $this->addSql('ALTER TABLE box_expense ADD CONSTRAINT FK_34F8139763DBB69 FOREIGN KEY (hospital_id) REFERENCES hospital (id)');
        $this->addSql('ALTER TABLE box_expense ADD CONSTRAINT FK_34F81397A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE box_expense ADD CONSTRAINT FK_34F8139712469DE2 FOREIGN KEY (category_id) REFERENCES expense_category (id)');
        $this->addSql('ALTER TABLE box_expense ADD CONSTRAINT FK_34F81397D8177B3F FOREIGN KEY (box_id) REFERENCES box (id)');
        $this->addSql('ALTER TABLE box_historic ADD CONSTRAINT FK_FC952DF2D8177B3F FOREIGN KEY (box_id) REFERENCES box (id)');
        $this->addSql('ALTER TABLE box_input ADD CONSTRAINT FK_A102EE3F63DBB69 FOREIGN KEY (hospital_id) REFERENCES hospital (id)');
        $this->addSql('ALTER TABLE box_input ADD CONSTRAINT FK_A102EE3FA76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE box_input ADD CONSTRAINT FK_A102EE3FD8177B3F FOREIGN KEY (box_id) REFERENCES box (id)');
        $this->addSql('ALTER TABLE box_output ADD CONSTRAINT FK_6276540863DBB69 FOREIGN KEY (hospital_id) REFERENCES hospital (id)');
        $this->addSql('ALTER TABLE box_output ADD CONSTRAINT FK_62765408A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE box_output ADD CONSTRAINT FK_6276540812469DE2 FOREIGN KEY (category_id) REFERENCES expense_category (id)');
        $this->addSql('ALTER TABLE box_output ADD CONSTRAINT FK_62765408D8177B3F FOREIGN KEY (box_id) REFERENCES box (id)');
        $this->addSql('ALTER TABLE consultation ADD CONSTRAINT FK_964685A66B899279 FOREIGN KEY (patient_id) REFERENCES patient (id)');
        $this->addSql('ALTER TABLE consultation ADD CONSTRAINT FK_964685A693CB796C FOREIGN KEY (file_id) REFERENCES consultations_type (id)');
        $this->addSql('ALTER TABLE consultation ADD CONSTRAINT FK_964685A663DBB69 FOREIGN KEY (hospital_id) REFERENCES hospital (id)');
        $this->addSql('ALTER TABLE consultation ADD CONSTRAINT FK_964685A6A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE consultation ADD CONSTRAINT FK_964685A687F4FB17 FOREIGN KEY (doctor_id) REFERENCES agent (id)');
        $this->addSql('ALTER TABLE consultation_act ADD CONSTRAINT FK_D236ADFE62FF6CDF FOREIGN KEY (consultation_id) REFERENCES consultation (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE consultation_act ADD CONSTRAINT FK_D236ADFED1A55B28 FOREIGN KEY (act_id) REFERENCES act (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE consultation_exam ADD CONSTRAINT FK_1372260C62FF6CDF FOREIGN KEY (consultation_id) REFERENCES consultation (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE consultation_exam ADD CONSTRAINT FK_1372260C578D5E91 FOREIGN KEY (exam_id) REFERENCES exam (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE consultation_treatment ADD CONSTRAINT FK_3EF32AD662FF6CDF FOREIGN KEY (consultation_id) REFERENCES consultation (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE consultation_treatment ADD CONSTRAINT FK_3EF32AD6471C0366 FOREIGN KEY (treatment_id) REFERENCES treatment (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE consultations_type ADD CONSTRAINT FK_DA0F005163DBB69 FOREIGN KEY (hospital_id) REFERENCES hospital (id)');
        $this->addSql('ALTER TABLE consumption_unit ADD CONSTRAINT FK_114B66C463DBB69 FOREIGN KEY (hospital_id) REFERENCES hospital (id)');
        $this->addSql('ALTER TABLE covenant ADD CONSTRAINT FK_F4EB80F763DBB69 FOREIGN KEY (hospital_id) REFERENCES hospital (id)');
        $this->addSql('ALTER TABLE covenant ADD CONSTRAINT FK_F4EB80F7F98F144A FOREIGN KEY (logo_id) REFERENCES image_object (id)');
        $this->addSql('ALTER TABLE covenant_invoice ADD CONSTRAINT FK_58A21C4463DBB69 FOREIGN KEY (hospital_id) REFERENCES hospital (id)');
        $this->addSql('ALTER TABLE covenant_invoice ADD CONSTRAINT FK_58A21C44DA91032A FOREIGN KEY (covenant_id) REFERENCES covenant (id)');
        $this->addSql('ALTER TABLE covenant_invoice ADD CONSTRAINT FK_58A21C44A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE department ADD CONSTRAINT FK_CD1DE18A63DBB69 FOREIGN KEY (hospital_id) REFERENCES hospital (id)');
        $this->addSql('ALTER TABLE destock_medicine_for_hospital ADD CONSTRAINT FK_5CD4372F2F7D140A FOREIGN KEY (medicine_id) REFERENCES medicine (id)');
        $this->addSql('ALTER TABLE destock_medicine_for_hospital ADD CONSTRAINT FK_5CD4372FA76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE destocking_of_medicines ADD CONSTRAINT FK_535BD9F2F7D140A FOREIGN KEY (medicine_id) REFERENCES medicine (id)');
        $this->addSql('ALTER TABLE destocking_of_medicines ADD CONSTRAINT FK_535BD9FA76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE drugstore_supply ADD CONSTRAINT FK_7F862433A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE drugstore_supply ADD CONSTRAINT FK_7F86243363DBB69 FOREIGN KEY (hospital_id) REFERENCES hospital (id)');
        $this->addSql('ALTER TABLE drugstore_supply ADD CONSTRAINT FK_7F862433A53A8AA FOREIGN KEY (provider_id) REFERENCES provider (id)');
        $this->addSql('ALTER TABLE drugstore_supply_medicine ADD CONSTRAINT FK_DC49F8AB55F5935 FOREIGN KEY (drugstore_supply_id) REFERENCES drugstore_supply (id)');
        $this->addSql('ALTER TABLE drugstore_supply_medicine ADD CONSTRAINT FK_DC49F8A2F7D140A FOREIGN KEY (medicine_id) REFERENCES medicine (id)');
        $this->addSql('ALTER TABLE exam ADD CONSTRAINT FK_38BBA6C663DBB69 FOREIGN KEY (hospital_id) REFERENCES hospital (id)');
        $this->addSql('ALTER TABLE exam ADD CONSTRAINT FK_38BBA6C612469DE2 FOREIGN KEY (category_id) REFERENCES exam_category (id)');
        $this->addSql('ALTER TABLE exam_category ADD CONSTRAINT FK_452856F263DBB69 FOREIGN KEY (hospital_id) REFERENCES hospital (id)');
        $this->addSql('ALTER TABLE exams_invoice_basket ADD CONSTRAINT FK_7782193A2989F1FD FOREIGN KEY (invoice_id) REFERENCES invoice (id)');
        $this->addSql('ALTER TABLE exams_invoice_basket ADD CONSTRAINT FK_7782193A578D5E91 FOREIGN KEY (exam_id) REFERENCES exam (id)');
        $this->addSql('ALTER TABLE expense_category ADD CONSTRAINT FK_C02DDB3863DBB69 FOREIGN KEY (hospital_id) REFERENCES hospital (id)');
        $this->addSql('ALTER TABLE hospital ADD CONSTRAINT FK_4282C85BA76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE hospital ADD CONSTRAINT FK_4282C85BF98F144A FOREIGN KEY (logo_id) REFERENCES image_object (id)');
        $this->addSql('ALTER TABLE hospitalization ADD CONSTRAINT FK_40CF089162FF6CDF FOREIGN KEY (consultation_id) REFERENCES consultation (id)');
        $this->addSql('ALTER TABLE hospitalization ADD CONSTRAINT FK_40CF089188688BB9 FOREIGN KEY (bed_id) REFERENCES bed (id)');
        $this->addSql('ALTER TABLE hospitalization ADD CONSTRAINT FK_40CF089163DBB69 FOREIGN KEY (hospital_id) REFERENCES hospital (id)');
        $this->addSql('ALTER TABLE image_object ADD CONSTRAINT FK_7B0F52463DBB69 FOREIGN KEY (hospital_id) REFERENCES hospital (id)');
        $this->addSql('ALTER TABLE invoice ADD CONSTRAINT FK_9065174463DBB69 FOREIGN KEY (hospital_id) REFERENCES hospital (id)');
        $this->addSql('ALTER TABLE invoice ADD CONSTRAINT FK_906517446B899279 FOREIGN KEY (patient_id) REFERENCES patient (id)');
        $this->addSql('ALTER TABLE invoice ADD CONSTRAINT FK_9065174462FF6CDF FOREIGN KEY (consultation_id) REFERENCES consultation (id)');
        $this->addSql('ALTER TABLE invoice ADD CONSTRAINT FK_90651744A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE invoice_storic ADD CONSTRAINT FK_DFA4BEF72989F1FD FOREIGN KEY (invoice_id) REFERENCES invoice (id)');
        $this->addSql('ALTER TABLE invoice_storic ADD CONSTRAINT FK_DFA4BEF7A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE invoice_storic ADD CONSTRAINT FK_DFA4BEF7936DC252 FOREIGN KEY (nursing_id) REFERENCES nursing (id)');
        $this->addSql('ALTER TABLE invoice_storic ADD CONSTRAINT FK_DFA4BEF7CF7D7FED FOREIGN KEY (covenant_invoice_id) REFERENCES covenant_invoice (id)');
        $this->addSql('ALTER TABLE lab ADD CONSTRAINT FK_61D6B1C463DBB69 FOREIGN KEY (hospital_id) REFERENCES hospital (id)');
        $this->addSql('ALTER TABLE lab ADD CONSTRAINT FK_61D6B1C4A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE lab ADD CONSTRAINT FK_61D6B1C462FF6CDF FOREIGN KEY (consultation_id) REFERENCES consultation (id)');
        $this->addSql('ALTER TABLE lab ADD CONSTRAINT FK_61D6B1C46B899279 FOREIGN KEY (patient_id) REFERENCES patient (id)');
        $this->addSql('ALTER TABLE lab ADD CONSTRAINT FK_61D6B1C476EF8C3F FOREIGN KEY (user_prescriber_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE lab ADD CONSTRAINT FK_61D6B1C4C00413CC FOREIGN KEY (user_publisher_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE lab_result ADD CONSTRAINT FK_86B24747628913D5 FOREIGN KEY (lab_id) REFERENCES lab (id)');
        $this->addSql('ALTER TABLE lab_result ADD CONSTRAINT FK_86B24747578D5E91 FOREIGN KEY (exam_id) REFERENCES exam (id)');
        $this->addSql('ALTER TABLE medicine ADD CONSTRAINT FK_58362A8D224EAF84 FOREIGN KEY (consumption_unit_id) REFERENCES consumption_unit (id)');
        $this->addSql('ALTER TABLE medicine ADD CONSTRAINT FK_58362A8D12469DE2 FOREIGN KEY (category_id) REFERENCES medicine_categories (id)');
        $this->addSql('ALTER TABLE medicine ADD CONSTRAINT FK_58362A8DF7BFE87C FOREIGN KEY (sub_category_id) REFERENCES medicine_sub_categories (id)');
        $this->addSql('ALTER TABLE medicine ADD CONSTRAINT FK_58362A8D63DBB69 FOREIGN KEY (hospital_id) REFERENCES hospital (id)');
        $this->addSql('ALTER TABLE medicine ADD CONSTRAINT FK_58362A8DA76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE medicine_categories ADD CONSTRAINT FK_665A0CBA63DBB69 FOREIGN KEY (hospital_id) REFERENCES hospital (id)');
        $this->addSql('ALTER TABLE medicine_invoice ADD CONSTRAINT FK_9D9E605AA76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE medicine_invoice ADD CONSTRAINT FK_9D9E605A63DBB69 FOREIGN KEY (hospital_id) REFERENCES hospital (id)');
        $this->addSql('ALTER TABLE medicine_sub_categories ADD CONSTRAINT FK_FA70B6DE12469DE2 FOREIGN KEY (category_id) REFERENCES medicine_categories (id)');
        $this->addSql('ALTER TABLE medicine_sub_categories ADD CONSTRAINT FK_FA70B6DE63DBB69 FOREIGN KEY (hospital_id) REFERENCES hospital (id)');
        $this->addSql('ALTER TABLE medicines_sold ADD CONSTRAINT FK_A1116C852F7D140A FOREIGN KEY (medicine_id) REFERENCES medicine (id)');
        $this->addSql('ALTER TABLE medicines_sold ADD CONSTRAINT FK_A1116C852989F1FD FOREIGN KEY (invoice_id) REFERENCES medicine_invoice (id)');
        $this->addSql('ALTER TABLE nursing ADD CONSTRAINT FK_883C8A1462FF6CDF FOREIGN KEY (consultation_id) REFERENCES consultation (id)');
        $this->addSql('ALTER TABLE nursing ADD CONSTRAINT FK_883C8A146B899279 FOREIGN KEY (patient_id) REFERENCES patient (id)');
        $this->addSql('ALTER TABLE nursing ADD CONSTRAINT FK_883C8A1463DBB69 FOREIGN KEY (hospital_id) REFERENCES hospital (id)');
        $this->addSql('ALTER TABLE nursing_treatment ADD CONSTRAINT FK_6138D4C8936DC252 FOREIGN KEY (nursing_id) REFERENCES nursing (id)');
        $this->addSql('ALTER TABLE nursing_treatment ADD CONSTRAINT FK_6138D4C8471C0366 FOREIGN KEY (treatment_id) REFERENCES treatment (id)');
        $this->addSql('ALTER TABLE nursing_treatment ADD CONSTRAINT FK_6138D4C8A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE office ADD CONSTRAINT FK_74516B0263DBB69 FOREIGN KEY (hospital_id) REFERENCES hospital (id)');
        $this->addSql('ALTER TABLE parameters ADD CONSTRAINT FK_69348FE63DBB69 FOREIGN KEY (hospital_id) REFERENCES hospital (id)');
        $this->addSql('ALTER TABLE patient ADD CONSTRAINT FK_1ADAD7EBA76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE patient ADD CONSTRAINT FK_1ADAD7EBDA91032A FOREIGN KEY (covenant_id) REFERENCES covenant (id)');
        $this->addSql('ALTER TABLE patient ADD CONSTRAINT FK_1ADAD7EBCCFA12B8 FOREIGN KEY (profile_id) REFERENCES image_object (id)');
        $this->addSql('ALTER TABLE patient ADD CONSTRAINT FK_1ADAD7EB63DBB69 FOREIGN KEY (hospital_id) REFERENCES hospital (id)');
        $this->addSql('ALTER TABLE personal_image_object ADD CONSTRAINT FK_E1053F56A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE prescription ADD CONSTRAINT FK_1FBFB8D962FF6CDF FOREIGN KEY (consultation_id) REFERENCES consultation (id)');
        $this->addSql('ALTER TABLE prescription ADD CONSTRAINT FK_1FBFB8D9628913D5 FOREIGN KEY (lab_id) REFERENCES lab (id)');
        $this->addSql('ALTER TABLE prescription ADD CONSTRAINT FK_1FBFB8D96B899279 FOREIGN KEY (patient_id) REFERENCES patient (id)');
        $this->addSql('ALTER TABLE prescription ADD CONSTRAINT FK_1FBFB8D9A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE prescription ADD CONSTRAINT FK_1FBFB8D963DBB69 FOREIGN KEY (hospital_id) REFERENCES hospital (id)');
        $this->addSql('ALTER TABLE provider ADD CONSTRAINT FK_92C4739C63DBB69 FOREIGN KEY (hospital_id) REFERENCES hospital (id)');
        $this->addSql('ALTER TABLE provider ADD CONSTRAINT FK_92C4739CA76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE reset_pass_notifier ADD CONSTRAINT FK_C158191CA76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE service ADD CONSTRAINT FK_E19D9AD263DBB69 FOREIGN KEY (hospital_id) REFERENCES hospital (id)');
        $this->addSql('ALTER TABLE service ADD CONSTRAINT FK_E19D9AD2AE80F5DF FOREIGN KEY (department_id) REFERENCES department (id)');
        $this->addSql('ALTER TABLE treatment ADD CONSTRAINT FK_98013C3163DBB69 FOREIGN KEY (hospital_id) REFERENCES hospital (id)');
        $this->addSql('ALTER TABLE treatment ADD CONSTRAINT FK_98013C3112469DE2 FOREIGN KEY (category_id) REFERENCES treatment_category (id)');
        $this->addSql('ALTER TABLE treatment_category ADD CONSTRAINT FK_94E6519863DBB69 FOREIGN KEY (hospital_id) REFERENCES hospital (id)');
        $this->addSql('ALTER TABLE user ADD CONSTRAINT FK_8D93D649A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE user ADD CONSTRAINT FK_8D93D64994CF6872 FOREIGN KEY (hospital_center_id) REFERENCES hospital (id)');
        $this->addSql('ALTER TABLE user ADD CONSTRAINT FK_8D93D649CCFA12B8 FOREIGN KEY (profile_id) REFERENCES personal_image_object (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE act DROP FOREIGN KEY FK_AFECF54463DBB69');
        $this->addSql('ALTER TABLE act DROP FOREIGN KEY FK_AFECF54412469DE2');
        $this->addSql('ALTER TABLE act_category DROP FOREIGN KEY FK_30337BDC63DBB69');
        $this->addSql('ALTER TABLE activities DROP FOREIGN KEY FK_B5F1AFE5F675F31B');
        $this->addSql('ALTER TABLE activities DROP FOREIGN KEY FK_B5F1AFE563DBB69');
        $this->addSql('ALTER TABLE acts_invoice_basket DROP FOREIGN KEY FK_18E3BB2E2989F1FD');
        $this->addSql('ALTER TABLE acts_invoice_basket DROP FOREIGN KEY FK_18E3BB2ED1A55B28');
        $this->addSql('ALTER TABLE agent DROP FOREIGN KEY FK_268B9C9D63DBB69');
        $this->addSql('ALTER TABLE agent DROP FOREIGN KEY FK_268B9C9DFFA0C224');
        $this->addSql('ALTER TABLE agent DROP FOREIGN KEY FK_268B9C9DED5CA9E6');
        $this->addSql('ALTER TABLE agent DROP FOREIGN KEY FK_268B9C9DA76ED395');
        $this->addSql('ALTER TABLE agent DROP FOREIGN KEY FK_268B9C9D3C0C9956');
        $this->addSql('ALTER TABLE appointment DROP FOREIGN KEY FK_FE38F84487F4FB17');
        $this->addSql('ALTER TABLE appointment DROP FOREIGN KEY FK_FE38F84462FF6CDF');
        $this->addSql('ALTER TABLE appointment DROP FOREIGN KEY FK_FE38F8446B899279');
        $this->addSql('ALTER TABLE appointment DROP FOREIGN KEY FK_FE38F84463DBB69');
        $this->addSql('ALTER TABLE appointment DROP FOREIGN KEY FK_FE38F844A76ED395');
        $this->addSql('ALTER TABLE bed DROP FOREIGN KEY FK_E647FCFF63DBB69');
        $this->addSql('ALTER TABLE bed DROP FOREIGN KEY FK_E647FCFFBDB6797C');
        $this->addSql('ALTER TABLE bedroom DROP FOREIGN KEY FK_E615435112469DE2');
        $this->addSql('ALTER TABLE bedroom DROP FOREIGN KEY FK_E615435163DBB69');
        $this->addSql('ALTER TABLE bedroom_category DROP FOREIGN KEY FK_1F4C876C63DBB69');
        $this->addSql('ALTER TABLE box DROP FOREIGN KEY FK_8A9483A63DBB69');
        $this->addSql('ALTER TABLE box_expense DROP FOREIGN KEY FK_34F8139763DBB69');
        $this->addSql('ALTER TABLE box_expense DROP FOREIGN KEY FK_34F81397A76ED395');
        $this->addSql('ALTER TABLE box_expense DROP FOREIGN KEY FK_34F8139712469DE2');
        $this->addSql('ALTER TABLE box_expense DROP FOREIGN KEY FK_34F81397D8177B3F');
        $this->addSql('ALTER TABLE box_historic DROP FOREIGN KEY FK_FC952DF2D8177B3F');
        $this->addSql('ALTER TABLE box_input DROP FOREIGN KEY FK_A102EE3F63DBB69');
        $this->addSql('ALTER TABLE box_input DROP FOREIGN KEY FK_A102EE3FA76ED395');
        $this->addSql('ALTER TABLE box_input DROP FOREIGN KEY FK_A102EE3FD8177B3F');
        $this->addSql('ALTER TABLE box_output DROP FOREIGN KEY FK_6276540863DBB69');
        $this->addSql('ALTER TABLE box_output DROP FOREIGN KEY FK_62765408A76ED395');
        $this->addSql('ALTER TABLE box_output DROP FOREIGN KEY FK_6276540812469DE2');
        $this->addSql('ALTER TABLE box_output DROP FOREIGN KEY FK_62765408D8177B3F');
        $this->addSql('ALTER TABLE consultation DROP FOREIGN KEY FK_964685A66B899279');
        $this->addSql('ALTER TABLE consultation DROP FOREIGN KEY FK_964685A693CB796C');
        $this->addSql('ALTER TABLE consultation DROP FOREIGN KEY FK_964685A663DBB69');
        $this->addSql('ALTER TABLE consultation DROP FOREIGN KEY FK_964685A6A76ED395');
        $this->addSql('ALTER TABLE consultation DROP FOREIGN KEY FK_964685A687F4FB17');
        $this->addSql('ALTER TABLE consultation_act DROP FOREIGN KEY FK_D236ADFE62FF6CDF');
        $this->addSql('ALTER TABLE consultation_act DROP FOREIGN KEY FK_D236ADFED1A55B28');
        $this->addSql('ALTER TABLE consultation_exam DROP FOREIGN KEY FK_1372260C62FF6CDF');
        $this->addSql('ALTER TABLE consultation_exam DROP FOREIGN KEY FK_1372260C578D5E91');
        $this->addSql('ALTER TABLE consultation_treatment DROP FOREIGN KEY FK_3EF32AD662FF6CDF');
        $this->addSql('ALTER TABLE consultation_treatment DROP FOREIGN KEY FK_3EF32AD6471C0366');
        $this->addSql('ALTER TABLE consultations_type DROP FOREIGN KEY FK_DA0F005163DBB69');
        $this->addSql('ALTER TABLE consumption_unit DROP FOREIGN KEY FK_114B66C463DBB69');
        $this->addSql('ALTER TABLE covenant DROP FOREIGN KEY FK_F4EB80F763DBB69');
        $this->addSql('ALTER TABLE covenant DROP FOREIGN KEY FK_F4EB80F7F98F144A');
        $this->addSql('ALTER TABLE covenant_invoice DROP FOREIGN KEY FK_58A21C4463DBB69');
        $this->addSql('ALTER TABLE covenant_invoice DROP FOREIGN KEY FK_58A21C44DA91032A');
        $this->addSql('ALTER TABLE covenant_invoice DROP FOREIGN KEY FK_58A21C44A76ED395');
        $this->addSql('ALTER TABLE department DROP FOREIGN KEY FK_CD1DE18A63DBB69');
        $this->addSql('ALTER TABLE destock_medicine_for_hospital DROP FOREIGN KEY FK_5CD4372F2F7D140A');
        $this->addSql('ALTER TABLE destock_medicine_for_hospital DROP FOREIGN KEY FK_5CD4372FA76ED395');
        $this->addSql('ALTER TABLE destocking_of_medicines DROP FOREIGN KEY FK_535BD9F2F7D140A');
        $this->addSql('ALTER TABLE destocking_of_medicines DROP FOREIGN KEY FK_535BD9FA76ED395');
        $this->addSql('ALTER TABLE drugstore_supply DROP FOREIGN KEY FK_7F862433A76ED395');
        $this->addSql('ALTER TABLE drugstore_supply DROP FOREIGN KEY FK_7F86243363DBB69');
        $this->addSql('ALTER TABLE drugstore_supply DROP FOREIGN KEY FK_7F862433A53A8AA');
        $this->addSql('ALTER TABLE drugstore_supply_medicine DROP FOREIGN KEY FK_DC49F8AB55F5935');
        $this->addSql('ALTER TABLE drugstore_supply_medicine DROP FOREIGN KEY FK_DC49F8A2F7D140A');
        $this->addSql('ALTER TABLE exam DROP FOREIGN KEY FK_38BBA6C663DBB69');
        $this->addSql('ALTER TABLE exam DROP FOREIGN KEY FK_38BBA6C612469DE2');
        $this->addSql('ALTER TABLE exam_category DROP FOREIGN KEY FK_452856F263DBB69');
        $this->addSql('ALTER TABLE exams_invoice_basket DROP FOREIGN KEY FK_7782193A2989F1FD');
        $this->addSql('ALTER TABLE exams_invoice_basket DROP FOREIGN KEY FK_7782193A578D5E91');
        $this->addSql('ALTER TABLE expense_category DROP FOREIGN KEY FK_C02DDB3863DBB69');
        $this->addSql('ALTER TABLE hospital DROP FOREIGN KEY FK_4282C85BA76ED395');
        $this->addSql('ALTER TABLE hospital DROP FOREIGN KEY FK_4282C85BF98F144A');
        $this->addSql('ALTER TABLE hospitalization DROP FOREIGN KEY FK_40CF089162FF6CDF');
        $this->addSql('ALTER TABLE hospitalization DROP FOREIGN KEY FK_40CF089188688BB9');
        $this->addSql('ALTER TABLE hospitalization DROP FOREIGN KEY FK_40CF089163DBB69');
        $this->addSql('ALTER TABLE image_object DROP FOREIGN KEY FK_7B0F52463DBB69');
        $this->addSql('ALTER TABLE invoice DROP FOREIGN KEY FK_9065174463DBB69');
        $this->addSql('ALTER TABLE invoice DROP FOREIGN KEY FK_906517446B899279');
        $this->addSql('ALTER TABLE invoice DROP FOREIGN KEY FK_9065174462FF6CDF');
        $this->addSql('ALTER TABLE invoice DROP FOREIGN KEY FK_90651744A76ED395');
        $this->addSql('ALTER TABLE invoice_storic DROP FOREIGN KEY FK_DFA4BEF72989F1FD');
        $this->addSql('ALTER TABLE invoice_storic DROP FOREIGN KEY FK_DFA4BEF7A76ED395');
        $this->addSql('ALTER TABLE invoice_storic DROP FOREIGN KEY FK_DFA4BEF7936DC252');
        $this->addSql('ALTER TABLE invoice_storic DROP FOREIGN KEY FK_DFA4BEF7CF7D7FED');
        $this->addSql('ALTER TABLE lab DROP FOREIGN KEY FK_61D6B1C463DBB69');
        $this->addSql('ALTER TABLE lab DROP FOREIGN KEY FK_61D6B1C4A76ED395');
        $this->addSql('ALTER TABLE lab DROP FOREIGN KEY FK_61D6B1C462FF6CDF');
        $this->addSql('ALTER TABLE lab DROP FOREIGN KEY FK_61D6B1C46B899279');
        $this->addSql('ALTER TABLE lab DROP FOREIGN KEY FK_61D6B1C476EF8C3F');
        $this->addSql('ALTER TABLE lab DROP FOREIGN KEY FK_61D6B1C4C00413CC');
        $this->addSql('ALTER TABLE lab_result DROP FOREIGN KEY FK_86B24747628913D5');
        $this->addSql('ALTER TABLE lab_result DROP FOREIGN KEY FK_86B24747578D5E91');
        $this->addSql('ALTER TABLE medicine DROP FOREIGN KEY FK_58362A8D224EAF84');
        $this->addSql('ALTER TABLE medicine DROP FOREIGN KEY FK_58362A8D12469DE2');
        $this->addSql('ALTER TABLE medicine DROP FOREIGN KEY FK_58362A8DF7BFE87C');
        $this->addSql('ALTER TABLE medicine DROP FOREIGN KEY FK_58362A8D63DBB69');
        $this->addSql('ALTER TABLE medicine DROP FOREIGN KEY FK_58362A8DA76ED395');
        $this->addSql('ALTER TABLE medicine_categories DROP FOREIGN KEY FK_665A0CBA63DBB69');
        $this->addSql('ALTER TABLE medicine_invoice DROP FOREIGN KEY FK_9D9E605AA76ED395');
        $this->addSql('ALTER TABLE medicine_invoice DROP FOREIGN KEY FK_9D9E605A63DBB69');
        $this->addSql('ALTER TABLE medicine_sub_categories DROP FOREIGN KEY FK_FA70B6DE12469DE2');
        $this->addSql('ALTER TABLE medicine_sub_categories DROP FOREIGN KEY FK_FA70B6DE63DBB69');
        $this->addSql('ALTER TABLE medicines_sold DROP FOREIGN KEY FK_A1116C852F7D140A');
        $this->addSql('ALTER TABLE medicines_sold DROP FOREIGN KEY FK_A1116C852989F1FD');
        $this->addSql('ALTER TABLE nursing DROP FOREIGN KEY FK_883C8A1462FF6CDF');
        $this->addSql('ALTER TABLE nursing DROP FOREIGN KEY FK_883C8A146B899279');
        $this->addSql('ALTER TABLE nursing DROP FOREIGN KEY FK_883C8A1463DBB69');
        $this->addSql('ALTER TABLE nursing_treatment DROP FOREIGN KEY FK_6138D4C8936DC252');
        $this->addSql('ALTER TABLE nursing_treatment DROP FOREIGN KEY FK_6138D4C8471C0366');
        $this->addSql('ALTER TABLE nursing_treatment DROP FOREIGN KEY FK_6138D4C8A76ED395');
        $this->addSql('ALTER TABLE office DROP FOREIGN KEY FK_74516B0263DBB69');
        $this->addSql('ALTER TABLE parameters DROP FOREIGN KEY FK_69348FE63DBB69');
        $this->addSql('ALTER TABLE patient DROP FOREIGN KEY FK_1ADAD7EBA76ED395');
        $this->addSql('ALTER TABLE patient DROP FOREIGN KEY FK_1ADAD7EBDA91032A');
        $this->addSql('ALTER TABLE patient DROP FOREIGN KEY FK_1ADAD7EBCCFA12B8');
        $this->addSql('ALTER TABLE patient DROP FOREIGN KEY FK_1ADAD7EB63DBB69');
        $this->addSql('ALTER TABLE personal_image_object DROP FOREIGN KEY FK_E1053F56A76ED395');
        $this->addSql('ALTER TABLE prescription DROP FOREIGN KEY FK_1FBFB8D962FF6CDF');
        $this->addSql('ALTER TABLE prescription DROP FOREIGN KEY FK_1FBFB8D9628913D5');
        $this->addSql('ALTER TABLE prescription DROP FOREIGN KEY FK_1FBFB8D96B899279');
        $this->addSql('ALTER TABLE prescription DROP FOREIGN KEY FK_1FBFB8D9A76ED395');
        $this->addSql('ALTER TABLE prescription DROP FOREIGN KEY FK_1FBFB8D963DBB69');
        $this->addSql('ALTER TABLE provider DROP FOREIGN KEY FK_92C4739C63DBB69');
        $this->addSql('ALTER TABLE provider DROP FOREIGN KEY FK_92C4739CA76ED395');
        $this->addSql('ALTER TABLE reset_pass_notifier DROP FOREIGN KEY FK_C158191CA76ED395');
        $this->addSql('ALTER TABLE service DROP FOREIGN KEY FK_E19D9AD263DBB69');
        $this->addSql('ALTER TABLE service DROP FOREIGN KEY FK_E19D9AD2AE80F5DF');
        $this->addSql('ALTER TABLE treatment DROP FOREIGN KEY FK_98013C3163DBB69');
        $this->addSql('ALTER TABLE treatment DROP FOREIGN KEY FK_98013C3112469DE2');
        $this->addSql('ALTER TABLE treatment_category DROP FOREIGN KEY FK_94E6519863DBB69');
        $this->addSql('ALTER TABLE user DROP FOREIGN KEY FK_8D93D649A76ED395');
        $this->addSql('ALTER TABLE user DROP FOREIGN KEY FK_8D93D64994CF6872');
        $this->addSql('ALTER TABLE user DROP FOREIGN KEY FK_8D93D649CCFA12B8');
        $this->addSql('DROP TABLE act');
        $this->addSql('DROP TABLE act_category');
        $this->addSql('DROP TABLE activities');
        $this->addSql('DROP TABLE acts_invoice_basket');
        $this->addSql('DROP TABLE agent');
        $this->addSql('DROP TABLE appointment');
        $this->addSql('DROP TABLE bed');
        $this->addSql('DROP TABLE bedroom');
        $this->addSql('DROP TABLE bedroom_category');
        $this->addSql('DROP TABLE box');
        $this->addSql('DROP TABLE box_expense');
        $this->addSql('DROP TABLE box_historic');
        $this->addSql('DROP TABLE box_input');
        $this->addSql('DROP TABLE box_output');
        $this->addSql('DROP TABLE consultation');
        $this->addSql('DROP TABLE consultation_act');
        $this->addSql('DROP TABLE consultation_exam');
        $this->addSql('DROP TABLE consultation_treatment');
        $this->addSql('DROP TABLE consultations_type');
        $this->addSql('DROP TABLE consumption_unit');
        $this->addSql('DROP TABLE covenant');
        $this->addSql('DROP TABLE covenant_invoice');
        $this->addSql('DROP TABLE department');
        $this->addSql('DROP TABLE destock_medicine_for_hospital');
        $this->addSql('DROP TABLE destocking_of_medicines');
        $this->addSql('DROP TABLE drugstore_supply');
        $this->addSql('DROP TABLE drugstore_supply_medicine');
        $this->addSql('DROP TABLE exam');
        $this->addSql('DROP TABLE exam_category');
        $this->addSql('DROP TABLE exams_invoice_basket');
        $this->addSql('DROP TABLE expense_category');
        $this->addSql('DROP TABLE hospital');
        $this->addSql('DROP TABLE hospitalization');
        $this->addSql('DROP TABLE image_object');
        $this->addSql('DROP TABLE invoice');
        $this->addSql('DROP TABLE invoice_storic');
        $this->addSql('DROP TABLE lab');
        $this->addSql('DROP TABLE lab_result');
        $this->addSql('DROP TABLE medicine');
        $this->addSql('DROP TABLE medicine_categories');
        $this->addSql('DROP TABLE medicine_invoice');
        $this->addSql('DROP TABLE medicine_sub_categories');
        $this->addSql('DROP TABLE medicines_sold');
        $this->addSql('DROP TABLE nursing');
        $this->addSql('DROP TABLE nursing_treatment');
        $this->addSql('DROP TABLE office');
        $this->addSql('DROP TABLE parameters');
        $this->addSql('DROP TABLE patient');
        $this->addSql('DROP TABLE pdf_object');
        $this->addSql('DROP TABLE personal_image_object');
        $this->addSql('DROP TABLE prescription');
        $this->addSql('DROP TABLE provider');
        $this->addSql('DROP TABLE reset_pass_notifier');
        $this->addSql('DROP TABLE service');
        $this->addSql('DROP TABLE treatment');
        $this->addSql('DROP TABLE treatment_category');
        $this->addSql('DROP TABLE user');
    }
}
